//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XenForms.Toolbox.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConnectResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConnectResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XenForms.Toolbox.UI.Resources.ConnectResource", typeof(ConnectResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to disconnect?.
        /// </summary>
        internal static string Are_you_sure_disconnect {
            get {
                return ResourceManager.GetString("Are_you_sure_disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to design surface....
        /// </summary>
        internal static string Connect_to_host {
            get {
                return ResourceManager.GetString("Connect_to_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect to a design surface.
        /// </summary>
        internal static string Connect_to_host_first {
            get {
                return ResourceManager.GetString("Connect_to_host_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Dialog_title {
            get {
                return ResourceManager.GetString("Dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to a design surface..
        /// </summary>
        internal static string Dialog_tooltip {
            get {
                return ResourceManager.GetString("Dialog_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from a design surface..
        /// </summary>
        internal static string Disconnect_tooltip {
            get {
                return ResourceManager.GetString("Disconnect_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string Host_label {
            get {
                return ResourceManager.GetString("Host_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Key.
        /// </summary>
        internal static string Key_label {
            get {
                return ResourceManager.GetString("Key_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed on design surface, if exists..
        /// </summary>
        internal static string Key_placeholder {
            get {
                return ResourceManager.GetString("Key_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Port_label {
            get {
                return ResourceManager.GetString("Port_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save designer address.
        /// </summary>
        internal static string Save_label {
            get {
                return ResourceManager.GetString("Save_label", resourceCulture);
            }
        }
    }
}
