//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XenForms.Toolbox.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ManagementSettingsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManagementSettingsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XenForms.Toolbox.UI.Resources.ManagementSettingsResource", typeof(ManagementSettingsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        internal static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly name.
        /// </summary>
        internal static string Assembly_name {
            get {
                return ResourceManager.GetString("Assembly_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Categories.
        /// </summary>
        internal static string Existing_Categories {
            get {
                return ResourceManager.GetString("Existing_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expandable.
        /// </summary>
        internal static string Expandable {
            get {
                return ResourceManager.GetString("Expandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework.
        /// </summary>
        internal static string Framework {
            get {
                return ResourceManager.GetString("Framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frameworks.
        /// </summary>
        internal static string Frameworks {
            get {
                return ResourceManager.GetString("Frameworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name.
        /// </summary>
        internal static string Property_name {
            get {
                return ResourceManager.GetString("Property_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only.
        /// </summary>
        internal static string Read_Only {
            get {
                return ResourceManager.GetString("Read_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Assemblies.
        /// </summary>
        internal static string Related_Assemblies {
            get {
                return ResourceManager.GetString("Related_Assemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Frameworks.
        /// </summary>
        internal static string Supported_Frameworks {
            get {
                return ResourceManager.GetString("Supported_Frameworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Properties.
        /// </summary>
        internal static string Supported_Properties {
            get {
                return ResourceManager.GetString("Supported_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a category name.
        /// </summary>
        internal static string Type_a_category_name {
            get {
                return ResourceManager.GetString("Type_a_category_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a framework name.
        /// </summary>
        internal static string Type_a_framework_name {
            get {
                return ResourceManager.GetString("Type_a_framework_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Editor.
        /// </summary>
        internal static string Type_Editor {
            get {
                return ResourceManager.GetString("Type_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are required to assign the Categories property before calling this method..
        /// </summary>
        internal static string You_are_required_to_assign_the_Categories_property_before_calling_this_method {
            get {
                return ResourceManager.GetString("You_are_required_to_assign_the_Categories_property_before_calling_this_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are required to assign the Frameworks property before calling this method..
        /// </summary>
        internal static string You_are_required_to_assign_the_Frameworks_property_before_calling_this_method {
            get {
                return ResourceManager.GetString("You_are_required_to_assign_the_Frameworks_property_before_calling_this_method", resourceCulture);
            }
        }
    }
}
