//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XenForms.Toolbox.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XenForms.Toolbox.UI.Resources.SettingsResource", typeof(SettingsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A child was not found for the Setting&apos;s group: {0}.
        /// </summary>
        internal static string A_child_was_not_found_for_the_settings_group {
            get {
                return ResourceManager.GetString("A_child_was_not_found_for_the_settings_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        internal static string Category_name {
            get {
                return ResourceManager.GetString("Category_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the root tree item..
        /// </summary>
        internal static string Could_not_find_root_tree_item {
            get {
                return ResourceManager.GetString("Could_not_find_root_tree_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Dialog_title {
            get {
                return ResourceManager.GetString("Dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Properties.
        /// </summary>
        internal static string Related_properties {
            get {
                return ResourceManager.GetString("Related_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The panel {0} couldn&apos;t be activated because it does not implement {1}.
        /// </summary>
        internal static string The_panel_couldnt_be_activated {
            get {
                return ResourceManager.GetString("The_panel_couldnt_be_activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root item was not assigned to the datastore..
        /// </summary>
        internal static string The_root_item_was_not_assigned_to_the_datastore {
            get {
                return ResourceManager.GetString("The_root_item_was_not_assigned_to_the_datastore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting panels were not found..
        /// </summary>
        internal static string The_settings_panels_were_not_found {
            get {
                return ResourceManager.GetString("The_settings_panels_were_not_found", resourceCulture);
            }
        }
    }
}
