//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XenForms.Designer.Tests.XML {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class XAMLTests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XAMLTests() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XenForms.Designer.Tests.XML.XAMLTests", typeof(XAMLTests).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Entry
        ///      xmlns=&quot;http://xamarin.com/schemas/2014/forms&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2009/xaml&quot;
        ///			AnchorX=&quot;0.5&quot;
        ///			AnchorY=&quot;0.5&quot;
        ///			AutomationId=&quot;{x:Null}&quot;
        ///			BackgroundColor=&quot;Default&quot;
        ///			BindingContext=&quot;{x:Null}&quot;
        ///			ClassId=&quot;{x:Null}&quot;
        ///			FontAttributes=&quot;Bold, Italic&quot;
        ///			FontFamily=&quot;{x:Null}&quot;
        ///			FontSize=&quot;18&quot;
        ///			HeightRequest=&quot;-1&quot;
        ///			HorizontalOptions=&quot;Fill&quot;
        ///			HorizontalTextAlignment=&quot;Start&quot;
        ///			InputTransparent=&quot;False&quot;
        ///			IsEnabled=&quot;True&quot;
        ///			IsPassword=&quot;False&quot;
        ///			IsVisib [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AP_Test1_Entry_Defaults {
            get {
                return ResourceManager.GetString("AP_Test1_Entry_Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ContentPage xmlns=&quot;http://xamarin.com/schemas/2014/forms&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2009/xaml&quot;&gt;
        ///  &lt;Entry
        ///        AnchorX=&quot;18&quot;
        ///        AnchorY=&quot;19&quot;
        ///        HorizontalOptions=&quot;Expand&quot;
        ///        AP.Test1=&quot;165&quot; /&gt;
        ///&lt;/ContentPage&gt;.
        /// </summary>
        public static string AP_Test1_Page {
            get {
                return ResourceManager.GetString("AP_Test1_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ContentPage x:Name=&quot;__ReferenceID0&quot; NavigationPage.BackButtonTitle=&quot;designer.xenforms.com&quot; NavigationPage.HasNavigationBar=&quot;True&quot; NavigationPage.HasBackButton=&quot;True&quot; NavigationPage.TitleIcon=&quot;{x:Null}&quot; AnchorX=&quot;0.5&quot; AnchorY=&quot;0.5&quot; BackgroundColor=&quot;Default&quot; HeightRequest=&quot;-1&quot; InputTransparent=&quot;False&quot; IsBusy=&quot;False&quot; IsEnabled=&quot;True&quot; IsVisible=&quot;True&quot; MinimumHeightRequest=&quot;-1&quot; MinimumWidthRequest=&quot;-1&quot; Opacity=&quot;1&quot; Padding=&quot;0&quot; Rotation=&quot;0&quot; RotationX=&quot;0&quot; RotationY=&quot;0&quot; Scale [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AP_Test1_Page_Default {
            get {
                return ResourceManager.GetString("AP_Test1_Page_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ContentPage x:Name=&quot;__ReferenceID0&quot; NavigationPage.BackButtonTitle=&quot;designer.xenforms.com&quot; NavigationPage.HasNavigationBar=&quot;True&quot; NavigationPage.HasBackButton=&quot;True&quot; NavigationPage.TitleIcon=&quot;{x:Null}&quot; AnchorX=&quot;0.5&quot; AnchorY=&quot;0.5&quot; BackgroundColor=&quot;Default&quot; HeightRequest=&quot;-1&quot; InputTransparent=&quot;False&quot; IsBusy=&quot;False&quot; IsEnabled=&quot;True&quot; IsVisible=&quot;True&quot; MinimumHeightRequest=&quot;-1&quot; MinimumWidthRequest=&quot;-1&quot; Opacity=&quot;1&quot; Padding=&quot;0&quot; Rotation=&quot;0&quot; RotationX=&quot;0&quot; RotationY=&quot;0&quot; Scale [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AP_Test1_Page_Modified {
            get {
                return ResourceManager.GetString("AP_Test1_Page_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Button
        ///     xmlns=&quot;http://xamarin.com/schemas/2014/forms&quot; 
        ///     xmlns:x=&quot;http://schemas.microsoft.com/winfx/2009/xaml&quot;
        ///     AnchorX=&quot;0.5&quot;
        ///     AnchorY=&quot;0.5&quot;
        ///     AutomationId=&quot;{x:Null}&quot;
        ///     BackgroundColor=&quot;Default&quot;
        ///     BindingContext=&quot;{x:Null}&quot;
        ///     BorderColor=&quot;Default&quot;
        ///     BorderRadius=&quot;5&quot;
        ///     BorderWidth=&quot;0&quot;
        ///     ClassId=&quot;{x:Null}&quot;
        ///     Command=&quot;{x:Null}&quot;
        ///     CommandParameter=&quot;{x:Null}&quot;
        ///     ContentLayout=&quot;Image Position = Left, Spacing = 10&quot;
        ///     Font=&quot;&quot;
        ///     FontAttributes=&quot;None&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Button_Defaults {
            get {
                return ResourceManager.GetString("Button_Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;DesignSurfacePage x:Name=&quot;__ReferenceID0&quot; AnchorX=&quot;0.5&quot; AnchorY=&quot;0.5&quot; AutomationId=&quot;{x:Null}&quot; BackgroundColor=&quot;Default&quot; BackgroundImage=&quot;{x:Null}&quot; BindingContext=&quot;{x:Null}&quot; ClassId=&quot;{x:Null}&quot; ControlTemplate=&quot;{x:Null}&quot; HeightRequest=&quot;-1&quot; Icon=&quot;{x:Null}&quot; InputTransparent=&quot;False&quot; IsBusy=&quot;False&quot; IsEnabled=&quot;True&quot; IsVisible=&quot;True&quot; MinimumHeightRequest=&quot;-1&quot; MinimumWidthRequest=&quot;-1&quot; Opacity=&quot;1&quot; Padding=&quot;0&quot; xmlns=&quot;http://xamarin.com/schemas/2014/forms&quot; xmlns:x=&quot;http://schem [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Button_Page {
            get {
                return ResourceManager.GetString("Button_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;DesignSurfacePage x:Name=&quot;__ReferenceID0&quot; AnchorX=&quot;0.5&quot; AnchorY=&quot;0.5&quot; AutomationId=&quot;{x:Null}&quot; BackgroundColor=&quot;Default&quot; BackgroundImage=&quot;{x:Null}&quot; BindingContext=&quot;{x:Null}&quot; ClassId=&quot;{x:Null}&quot; ControlTemplate=&quot;{x:Null}&quot; HeightRequest=&quot;-1&quot; Icon=&quot;{x:Null}&quot; InputTransparent=&quot;False&quot; IsBusy=&quot;False&quot; IsEnabled=&quot;True&quot; IsVisible=&quot;True&quot; MinimumHeightRequest=&quot;-1&quot; MinimumWidthRequest=&quot;-1&quot; Opacity=&quot;1&quot; Padding=&quot;0&quot; xmlns=&quot;http://xamarin.com/schemas/2014/forms&quot; xmlns:x=&quot;http://schem [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Button_Page_Defaults {
            get {
                return ResourceManager.GetString("Button_Page_Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ContentPage xmlns=&quot;http://xamarin.com/schemas/2014/forms&quot;
        ///             xmlns:x=&quot;http://schemas.microsoft.com/winfx/2009/xaml&quot;
        ///             x:Class=&quot;Events.SliderAndButton&quot;&gt;
        ///  &lt;StackLayout&gt;
        ///    &lt;Slider VerticalOptions=&quot;CenterAndExpand&quot;
        ///            ValueChanged=&quot;OnSliderValueChanged&quot; /&gt;
        ///
        ///    &lt;Label Text=&quot;A simple Label&quot;
        ///           x:Name=&quot;valueLabel&quot;
        ///           HorizontalOptions=&quot;Center&quot;
        ///           VerticalOptions=&quot;CenterAndExpand&quot; /&gt;
        ///
        ///    &lt;Button Text=&quot;Cl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CustomPageType {
            get {
                return ResourceManager.GetString("CustomPageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;DesignSurfacePage xmlns=&quot;http://xamarin.com/schemas/2014/forms&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2009/xaml&quot;&gt;
        ///  &lt;DesignSurfacePage.Parent&gt;&lt;/DesignSurfacePage.Parent&gt;
        ///  &lt;Other&gt;&lt;/Other&gt;
        ///&lt;/DesignSurfacePage&gt;.
        /// </summary>
        public static string DesignSurfaceElement {
            get {
                return ResourceManager.GetString("DesignSurfaceElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Entry
        ///      xmlns=&quot;http://xamarin.com/schemas/2014/forms&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2009/xaml&quot;
        ///			AnchorX=&quot;0.5&quot;
        ///			AnchorY=&quot;0.5&quot;
        ///			AutomationId=&quot;{x:Null}&quot;
        ///			BackgroundColor=&quot;#FFFFFF&quot;
        ///			BindingContext=&quot;{x:Null}&quot;
        ///			ClassId=&quot;{x:Null}&quot;
        ///			FontAttributes=&quot;Bold, Italic&quot;
        ///			FontFamily=&quot;{x:Null}&quot;
        ///			FontSize=&quot;18&quot;
        ///			HeightRequest=&quot;-1&quot;
        ///			HorizontalOptions=&quot;Fill&quot;
        ///			HorizontalTextAlignment=&quot;Start&quot;
        ///			InputTransparent=&quot;False&quot;
        ///			IsEnabled=&quot;True&quot;
        ///			IsPassword=&quot;False&quot;
        ///			IsVisib [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Entry_Defaults {
            get {
                return ResourceManager.GetString("Entry_Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;DesignSurfacePage x:Name=&quot;__ReferenceID0&quot; AnchorX=&quot;0.5&quot; AnchorY=&quot;0.5&quot; AutomationId=&quot;{x:Null}&quot; BackgroundColor=&quot;Default&quot; BackgroundImage=&quot;{x:Null}&quot; BindingContext=&quot;{x:Null}&quot; ClassId=&quot;{x:Null}&quot; ControlTemplate=&quot;{x:Null}&quot; HeightRequest=&quot;-1&quot; Icon=&quot;{x:Null}&quot; InputTransparent=&quot;False&quot; IsBusy=&quot;False&quot; IsEnabled=&quot;True&quot; IsVisible=&quot;True&quot; MinimumHeightRequest=&quot;-1&quot; MinimumWidthRequest=&quot;-1&quot; Opacity=&quot;1&quot; Padding=&quot;0&quot; xmlns=&quot;http://xamarin.com/schemas/2014/forms&quot; xmlns:x=&quot;http://schem [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Entry_Page {
            get {
                return ResourceManager.GetString("Entry_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;DesignSurfacePage x:Name=&quot;__ReferenceID0&quot; AnchorX=&quot;0.5&quot; AnchorY=&quot;0.5&quot; AutomationId=&quot;{x:Null}&quot; BackgroundColor=&quot;Default&quot; BackgroundImage=&quot;{x:Null}&quot; BindingContext=&quot;{x:Null}&quot; ClassId=&quot;{x:Null}&quot; ControlTemplate=&quot;{x:Null}&quot; HeightRequest=&quot;-1&quot; Icon=&quot;{x:Null}&quot; InputTransparent=&quot;False&quot; IsBusy=&quot;False&quot; IsEnabled=&quot;True&quot; IsVisible=&quot;True&quot; MinimumHeightRequest=&quot;-1&quot; MinimumWidthRequest=&quot;-1&quot; Opacity=&quot;1&quot; Padding=&quot;0&quot; xmlns=&quot;http://xamarin.com/schemas/2014/forms&quot; xmlns:x=&quot;http://schem [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Entry_Page_Defaults {
            get {
                return ResourceManager.GetString("Entry_Page_Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ContentPage AnchorX=&quot;0.5&quot; AnchorY=&quot;0.5&quot; BackgroundColor=&quot;Default&quot; HeightRequest=&quot;-1&quot; InputTransparent=&quot;False&quot; IsBusy=&quot;False&quot; IsEnabled=&quot;True&quot; IsVisible=&quot;True&quot; MinimumHeightRequest=&quot;-1&quot; MinimumWidthRequest=&quot;-1&quot; Opacity=&quot;1&quot; Padding=&quot;0&quot; Rotation=&quot;0&quot; RotationX=&quot;0&quot; RotationY=&quot;0&quot; Scale=&quot;1&quot; TranslationX=&quot;0&quot; TranslationY=&quot;0&quot; WidthRequest=&quot;-1&quot; AutomationId=&quot;{x:Null}&quot; BackgroundImage=&quot;{x:Null}&quot; BindingContext=&quot;{x:Null}&quot; ClassId=&quot;{x:Null}&quot; ControlTemplate=&quot;{x:Null}&quot; Icon=&quot;{x:N [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Nulls_ContentPage_Defaults {
            get {
                return ResourceManager.GetString("Nulls_ContentPage_Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ContentPage x:Name=&quot;__ReferenceID0&quot; NavigationPage.BackButtonTitle=&quot;designer.xenforms.com&quot; NavigationPage.HasNavigationBar=&quot;True&quot; NavigationPage.HasBackButton=&quot;True&quot; NavigationPage.TitleIcon=&quot;{x:Null}&quot; AnchorX=&quot;0.5&quot; AnchorY=&quot;0.5&quot; BackgroundColor=&quot;Default&quot; HeightRequest=&quot;-1&quot; InputTransparent=&quot;False&quot; IsBusy=&quot;False&quot; IsEnabled=&quot;True&quot; IsVisible=&quot;True&quot; MinimumHeightRequest=&quot;-1&quot; MinimumWidthRequest=&quot;-1&quot; Opacity=&quot;1&quot; Padding=&quot;0&quot; Rotation=&quot;0&quot; RotationX=&quot;0&quot; RotationY=&quot;0&quot; Scale [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Nulls_Input {
            get {
                return ResourceManager.GetString("Nulls_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Label AnchorX=&quot;0.5&quot; AnchorY=&quot;0.5&quot; BackgroundColor=&quot;Default&quot; Font=&quot;&quot; FontAttributes=&quot;None&quot; FontSize=&quot;13.980582524271844&quot; HeightRequest=&quot;-1&quot; HorizontalOptions=&quot;Fill&quot; HorizontalTextAlignment=&quot;Start&quot; InputTransparent=&quot;False&quot; IsEnabled=&quot;True&quot; IsVisible=&quot;True&quot; LineBreakMode=&quot;WordWrap&quot; Margin=&quot;0&quot; MinimumHeightRequest=&quot;-1&quot; MinimumWidthRequest=&quot;-1&quot; Opacity=&quot;1&quot; Rotation=&quot;0&quot; RotationX=&quot;0&quot; RotationY=&quot;0&quot; Scale=&quot;1&quot; TextColor=&quot;Default&quot; TranslationX=&quot;0&quot; TranslationY=&quot;0&quot; VerticalOpt [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Nulls_Label_Defaults {
            get {
                return ResourceManager.GetString("Nulls_Label_Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;DesignSurfacePage xmlns=&quot;http://xamarin.com/schemas/2014/forms&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2009/xaml&quot;&gt;
        ///  &lt;Entry
        ///        xmlns=&quot;http://xamarin.com/schemas/2014/forms&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2009/xaml&quot;
        ///        AnchorX=&quot;0.5&quot;
        ///        AnchorY=&quot;0.5&quot;
        ///        AutomationId=&quot;{x:Null}&quot;
        ///        BackgroundColor=&quot;#FFFFFF&quot;
        ///        BindingContext=&quot;{x:Null}&quot;
        ///        ClassId=&quot;{x:Null}&quot;
        ///        FontAttributes=&quot;Bold, Italic&quot;
        ///        FontF [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TreeReader1 {
            get {
                return ResourceManager.GetString("TreeReader1", resourceCulture);
            }
        }
    }
}
